gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - site_tool
  - README.adoc
  - Gemfile*
  - tmp

# When writing a blog post, you can use this special HTML comment to
# designate where the post should be chopped in order to generate the
# excerpt on the main blog page.
excerpt_separator: "<!--more-->"

# Force using kramdown as the markdown generator, since it supports the
# TOC function we use on the FAQ page.
markdown: kramdown

kramdown:
    toc_levels: 1..3
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

# Pagination settings for the blog.
paginate: 5
paginate_path: "/blog/page/:num"
